config/routes.rb
Rails.application.routes.draw do
  root to: "pages#homepage"
  get "home", to: "pages#homepage"
  get "help/mobile", to: "pages#help"
  get "plans", to: "plans#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def homepage
  end

  def help
    @name = "Peter"
  end

  def plans

  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  def index
    @plans = ["plan1", "plan2"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/layouts/_body.html.erb
<h1>Pages#homepage</h1>
<!--BIG PURPLE CONTAINER  -->
<div class="bg-purple container-fluid">
  <div class="row">
    <div class="col-sm-12 col-lg-6">
      <p class="text-white" id="google_home"><strong>win a Google Home, Chromecast Ultra and a year of nbn™</strong></p>
      <p class= "text-white" id="signUp">Sign up to any nbn plan before 31 August to go into the draw. Plans start from $40 a month.</p>
      <a href="#" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">sign up ></a>
    </div>
    <div class="col-sm-12 col-lg-6">
      <%= image_tag "Header_Image-nbn-com-2.png" %>
    </div>
  </div>
</div>

<!--SMALL MENU  -->
<div class="bg white container-fluid">
  <div class="row">
    <div class="container col-lg-4">
      <div class="row">
        <div class="container col-lg-2">
          <%= image_tag "lock_dash_mint.svg"%>
        </div>
        <div class="container col-lg-10">
          <h4>no lock-in contracts</h4>
          <p>Freedom to switch your plan or cancel at anytime.</p>
        </div>
      </div>
    </div>

    <div class="container col-lg-4">
      <div class="row">
        <div class="container col-lg-2">
          <%= image_tag "join_dash_mint.svg"%>
        </div>
        <div class="container col-lg-10">
          <h4>simple to join</h4>
          <p>Quick and easy online sign-up, we’ll take care of all the fiddly bits.</p>
        </div>
      </div>
    </div>

    <div class="container col-lg-4">
      <div class="row">
        <div class="container col-lg-2">
          <%= image_tag "app_dash_mint.svg"%>
        </div>
        <div class="container col-lg-10">
          <h4>easy to manage</h4>
          <p><a href="#">Download our app</a> or manage your plans online.</p>
        </div>
      </div>
    </div>




<!--CARDS  -->
  <div class="row">
    <div class="col-lg-4">

        <div class="card" style="width: 30rem;">
          <div class="card-body">
            <h4>sim-only mobile plans</h4>
            <p>Unlimited standard talk &amp; text with heaps of data for use in Oz.</p>
          </div>
          <%= image_tag "mobile plans.png", class: "card-img-top"%>
          <div class="card-footer">
            <small class="text-muted">mobile plans</small>
          </div>
        </div>

    </div>

    <div class="col-lg-4">

        <div class="card" style="width: 30rem;">
          <div class="card-body">
            <h4>nbn broadband plans</h4>
            <p>Unlimited data with superfast speeds. No lock-in contracts.</p>
          </div>
          <%= image_tag "nbn.png", class: "card-img-top"%>
          <div class="card-footer">
            <small class="text-muted">nbn plans</small>
          </div>
        </div>

    </div>

        <div class="col-lg-4">

            <div class="card" style="width: 30rem;">
              <div class="card-body">
                <h4>data-only plans</h4>
                <p>Mobile broadband for your tablets and devices, for use in Oz.</p>
              </div>
              <%= image_tag "data only.png", class: "card-img-top"%>
              <div class="card-footer">
                <small class="text-muted">data-only plans</small>
              </div>
            </div>

        </div>
    </div>
</div>

    <div class="bg-purple container-fluid">
      <div class="row">
        <div class="col-sm-12 col-lg-4">
          <%= image_tag "website_award_2016-2017.png"%>
        </div>
        <div class="col-sm-12 col-lg-4">
          <p class="text-white"><strong>93% of our customers have recommended amaysim to their mates</strong></p>
          <p class="text-white">NPS tracking survey of 2679 customers, May 2017</p>
        </div>
        <div class="col-sm-12 col-lg-4">
          <a href="#" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">compare plans ></a>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <h2>what we've been up to</h2>
      </div>
    </div>

  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <h4>we've been named best VNO</h4>
        <p>Delivering on the promises that we made to Aussies 6 years ago.</p>
        <a href="#" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">read all about it ></a>
      </div>

      <div class="col-lg-6">
        <h4>What a two year mobile phone contract will really cost you</h4>
        <p>14 Sep 2016 in <a href="#">Tech Talk</a></p>

        <h4>Check out our new and improved Help section</h4>
        <p>14 Sep 2016 in <a href="#">Plans &amp; Services</a></p>

        <h4>AS YOU GO credit now lasts for 365 days</h4>
        <p>16 Aug 2016 in <a href="#">Plans &amp; Services</a></p>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <h2>already with amaysim?</h2>
      </div>
    </div>

<div class="svg-sprite icon__has-canvas">
  <canvas height width viewbox="0 0 79.79664 79.79664">
    <svg height width viewbox="0 0 79.79664 79.79664"></svg>
    <svg id="icon_sim" viewBox="0 0 86.6 79.8" fill="#F50" width="100%">
    <path d="M83.1 42.9L43.7 3.5c-4.7-4.7-12.3-4.7-17 0L3.5 26.7c-4.7 4.7-4.7 12.3 0 17l27.9 27.9c11 11 29.1 11 40.1 0L83.1 60c4.7-4.8 4.7-12.4 0-17.1zm-9 13.7l-7.6 7.6c-8.3 8.3-21.8 8.3-30.1 0L12.5 40.4c-2.9-2.9-2.9-7.6 0-10.4L30 12.5c2.9-2.9 7.6-2.9 10.4 0l33.7 33.7c2.8 2.9 2.8 7.6 0 10.4z"></path>
    <path d="M44.4 31.7l-3.1 3.1c-1.7 1.7-4.4 1.7-6 0l-6-6c-1.7-1.7-1.7-4.4 0-6l3.1-3.1c1.7-1.7 4.4-1.7 6 0l6 6c1.7 1.6 1.7 4.3 0 6z"></path>
  </svg>
    <p>activate sim</p>
</div>



    <p>recharge plan</p>

    <p>manage account</p>

    <p>need help</p>

app/views/layouts/_nav.html.erb
<!-- _nav.html.erb -->

<nav class="navbar navbar-expand-lg navbar-light bg-color">
  <%= link_to "amaysim", home_url, class: "navbar-brand text-white"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Plans
        <span class="sr-only">(current)</span></a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">mobile plans</a>
          <a class="dropdown-item" href="#">nbn plans</a>
          <a class="dropdown-item" href="#">data-only plans</a>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          About
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">who we are</a>
          <a class="dropdown-item" href="#">why amaysim</a>
          <a class="dropdown-item" href="#">check mobile network coverage</a>
          <a class="dropdown-item" href="#">find a store</a>
          <a class="dropdown-item" href="#">read our block</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/help/mobile">Help</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amaysim</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- <a href="/help/mobile">Help</a> -->
    <!-- <%= link_to "Help", help_mobile_path%> -->
    <!-- <%= link_to "Help URL", help_mobile_url%> -->

    <%= render "layouts/nav"%>
    
    <%= yield %>
  </body>
</html>

app/views/pages/help.html.erb
<h1>what can we help you with?</h1>
<p>Find me in app/views/pages/help.html.erb</p>

<h1>
  <%= @name %>
  <p>This is a result of a method coming from the method located in the pages controller.</p>
</h1>

app/views/pages/homepage.html.erb
<%= render "layouts/body"%>

app/views/plans/index.html.erb
<h1>Hi there</h1>

<% @plans.each_with_index do |plan, index| %>
  <!-- <h3>blah</h3><br> -->
  <% if index == 1 %>
    <div class="alert alert-success" role="alert">
        <%= plan %><br>
    </div>
  <% else %>
    <div class="alert alert-danger" role="alert">
        <%= plan %><br>
    </div>
  <% end %>
<% end %>